// AUTO-GENERATED fd.o2r manifest.
#ifndef FD_O2R_MANIFEST_H
#define FD_O2R_MANIFEST_H
#include <array>
#include <cstdint>

static const std::array<const char*, 137> kFdRomDerivedPaths = {
    "misc/link_animetion/gPlayerAnim_cl_maskoff_Data",
    "misc/link_animetion/gPlayerAnim_cl_setmask_Data",
    "misc/link_animetion/gPlayerAnim_cl_setmaskend_Data",
    "misc/link_animetion/gPlayerAnim_pg_maskoffstart_Data",
    "misc/link_animetion/gPlayerAnim_pn_maskoffstart_Data",
    "misc/link_animetion/gPlayerAnim_pz_maskoffstart_Data",
    "objects/gameplay_keep/gFierceDeityMaskDL",
    "objects/gameplay_keep/gFierceDeityMaskEarTex",
    "objects/gameplay_keep/gFierceDeityMaskEyesTex",
    "objects/gameplay_keep/gFierceDeityMaskHairTex",
    "objects/gameplay_keep/gFierceDeityMaskHatTex",
    "objects/gameplay_keep/gFierceDeityMaskMouthTex",
    "objects/gameplay_keep/gFierceDeityMaskTLUT",
    "objects/gameplay_keep/gPlayerAnim_cl_maskoff",
    "objects/gameplay_keep/gPlayerAnim_cl_setmask",
    "objects/gameplay_keep/gPlayerAnim_cl_setmaskend",
    "objects/gameplay_keep/gPlayerAnim_pg_maskoffstart",
    "objects/gameplay_keep/gPlayerAnim_pn_maskoffstart",
    "objects/gameplay_keep/gPlayerAnim_pz_maskoffstart",
    "objects/gameplay_keep/gameplay_keepVtx_00A940",
    "objects/object_gi_mask03/gGiFierceDeityMaskEarTex",
    "objects/object_gi_mask03/gGiFierceDeityMaskEyeTLUT",
    "objects/object_gi_mask03/gGiFierceDeityMaskEyeTex",
    "objects/object_gi_mask03/gGiFierceDeityMaskFaceDL",
    "objects/object_gi_mask03/gGiFierceDeityMaskHairTex",
    "objects/object_gi_mask03/gGiFierceDeityMaskHatTex",
    "objects/object_gi_mask03/gGiFierceDeityMaskMouthAndEarTLUT",
    "objects/object_gi_mask03/gGiFierceDeityMaskMouthTex",
    "objects/object_gi_mask03/object_gi_mask03Vtx_000000",
    "objects/object_gi_mask03/object_gi_mask03Vtx_000520",
    "objects/object_link_boy/gLinkFierceDeityBottleDL",
    "objects/object_link_boy/gLinkFierceDeityCollarLimb",
    "objects/object_link_boy/gLinkFierceDeityEarTex",
    "objects/object_link_boy/gLinkFierceDeityEmptyDL",
    "objects/object_link_boy/gLinkFierceDeityEyesTex",
    "objects/object_link_boy/gLinkFierceDeityHandHoldingTLUT",
    "objects/object_link_boy/gLinkFierceDeityHandHoldingTex",
    "objects/object_link_boy/gLinkFierceDeityHandTLUT",
    "objects/object_link_boy/gLinkFierceDeityHandTex",
    "objects/object_link_boy/gLinkFierceDeityHatDL",
    "objects/object_link_boy/gLinkFierceDeityHatLimb",
    "objects/object_link_boy/gLinkFierceDeityHeadDL",
    "objects/object_link_boy/gLinkFierceDeityHeadLimb",
    "objects/object_link_boy/gLinkFierceDeityLeftFootDL",
    "objects/object_link_boy/gLinkFierceDeityLeftFootLimb",
    "objects/object_link_boy/gLinkFierceDeityLeftForearmDL",
    "objects/object_link_boy/gLinkFierceDeityLeftForearmLimb",
    "objects/object_link_boy/gLinkFierceDeityLeftHandDL",
    "objects/object_link_boy/gLinkFierceDeityLeftHandHoldBottleDL",
    "objects/object_link_boy/gLinkFierceDeityLeftHandHoldingSwordDL",
    "objects/object_link_boy/gLinkFierceDeityLeftHandLimb",
    "objects/object_link_boy/gLinkFierceDeityLeftShinDL",
    "objects/object_link_boy/gLinkFierceDeityLeftShinLimb",
    "objects/object_link_boy/gLinkFierceDeityLeftShoulderDL",
    "objects/object_link_boy/gLinkFierceDeityLeftShoulderLimb",
    "objects/object_link_boy/gLinkFierceDeityLeftThighDL",
    "objects/object_link_boy/gLinkFierceDeityLeftThighLimb",
    "objects/object_link_boy/gLinkFierceDeityLowerRootLimb",
    "objects/object_link_boy/gLinkFierceDeityMouthTex",
    "objects/object_link_boy/gLinkFierceDeityRightFootDL",
    "objects/object_link_boy/gLinkFierceDeityRightFootLimb",
    "objects/object_link_boy/gLinkFierceDeityRightForearmDL",
    "objects/object_link_boy/gLinkFierceDeityRightForearmLimb",
    "objects/object_link_boy/gLinkFierceDeityRightHandDL",
    "objects/object_link_boy/gLinkFierceDeityRightHandLimb",
    "objects/object_link_boy/gLinkFierceDeityRightShinDL",
    "objects/object_link_boy/gLinkFierceDeityRightShinLimb",
    "objects/object_link_boy/gLinkFierceDeityRightShoulderDL",
    "objects/object_link_boy/gLinkFierceDeityRightShoulderLimb",
    "objects/object_link_boy/gLinkFierceDeityRightThighDL",
    "objects/object_link_boy/gLinkFierceDeityRightThighLimb",
    "objects/object_link_boy/gLinkFierceDeityRootLimb",
    "objects/object_link_boy/gLinkFierceDeitySheathLimb",
    "objects/object_link_boy/gLinkFierceDeitySkel",
    "objects/object_link_boy/gLinkFierceDeitySkelLimbs",
    "objects/object_link_boy/gLinkFierceDeitySwordDL",
    "objects/object_link_boy/gLinkFierceDeityTorsoDL",
    "objects/object_link_boy/gLinkFierceDeityTorsoLimb",
    "objects/object_link_boy/gLinkFierceDeityUpperRootLimb",
    "objects/object_link_boy/gLinkFierceDeityWaistDL",
    "objects/object_link_boy/gLinkFierceDeityWaistLimb",
    "objects/object_link_boy/object_link_boyVtx_000C00",
    "objects/object_link_boy/object_link_boyVtx_000E90",
    "objects/object_link_boy/object_link_boyVtx_001210",
    "objects/object_link_boy/object_link_boyVtx_001560",
    "objects/object_link_boy/object_link_boyVtx_0017F0",
    "objects/object_link_boy/object_link_boyVtx_001B80",
    "objects/object_link_boy/object_link_boyVtx_001EE0",
    "objects/object_link_boy/object_link_boyVtx_002210",
    "objects/object_link_boy/object_link_boyVtx_002440",
    "objects/object_link_boy/object_link_boyVtx_003270",
    "objects/object_link_boy/object_link_boyVtx_003600",
    "objects/object_link_boy/object_link_boyVtx_0038F0",
    "objects/object_link_boy/object_link_boyVtx_003BD0",
    "objects/object_link_boy/object_link_boyVtx_003D50",
    "objects/object_link_boy/object_link_boyVtx_0040E0",
    "objects/object_link_boy/object_link_boyVtx_0043D0",
    "objects/object_link_boy/object_link_boyVtx_004670",
    "objects/object_link_boy/object_link_boyVtx_004980",
    "objects/object_link_boy/object_link_boyVtx_007110",
    "objects/object_link_boy/object_link_boyVtx_0073A0",
    "objects/object_link_boy/object_link_boyVtx_007440",
    "objects/object_link_boy/object_link_boyVtx_007BE8",
    "objects/object_link_boy/object_link_boy_DL_0060E8",
    "objects/object_link_boy/object_link_boy_DL_006370",
    "objects/object_link_boy/object_link_boy_DL_007A50",
    "objects/object_link_boy/object_link_boy_TLUT_000000",
    "objects/object_link_boy/object_link_boy_TLUT_000200",
    "objects/object_link_boy/object_link_boy_TLUT_008108",
    "objects/object_link_boy/object_link_boy_TLUT_008128",
    "objects/object_link_boy/object_link_boy_TLUT_008148",
    "objects/object_link_boy/object_link_boy_TLUT_008168",
    "objects/object_link_boy/object_link_boy_TLUT_008188",
    "objects/object_link_boy/object_link_boy_TLUT_0081A8",
    "objects/object_link_boy/object_link_boy_TLUT_0081E8",
    "objects/object_link_boy/object_link_boy_Tex_000600",
    "objects/object_link_boy/object_link_boy_Tex_000800",
    "objects/object_link_boy/object_link_boy_Tex_000B00",
    "objects/object_link_boy/object_link_boy_Tex_008208",
    "objects/object_link_boy/object_link_boy_Tex_008408",
    "objects/object_link_boy/object_link_boy_Tex_008488",
    "objects/object_link_boy/object_link_boy_Tex_008888",
    "objects/object_link_boy/object_link_boy_Tex_008C88",
    "objects/object_link_boy/object_link_boy_Tex_008D08",
    "objects/object_link_boy/object_link_boy_Tex_008F08",
    "objects/object_link_boy/object_link_boy_Tex_00A708",
    "objects/object_link_boy/object_link_boy_Tex_00AF08",
    "objects/object_link_boy/object_link_boy_Tex_00B188",
    "objects/object_link_boy/object_link_boy_Tex_00B988",
    "objects/object_mask_boy/object_mask_boyVtx_000000",
    "objects/object_mask_boy/object_mask_boy_DL_000900",
    "objects/object_mask_boy/object_mask_boy_TLUT_000D50",
    "objects/object_mask_boy/object_mask_boy_Tex_000F50",
    "objects/object_mask_boy/object_mask_boy_Tex_001350",
    "objects/object_mask_boy/object_mask_boy_Tex_001B50",
    "objects/object_mask_boy/object_mask_boy_Tex_001F50",
    "objects/object_mask_boy/object_mask_boy_Tex_002050",
};

static constexpr const char* kFdPatchedDlPath = "objects/object_gi_mask03/gGiFierceDeityMaskHairAndHatDL";
struct FdBytePatch { uint32_t offset; uint8_t value; };
static const std::array<FdBytePatch, 2> kFdPatchedDlBytes = {{
    { 425u, 0xfe },
    { 426u, 0x30 },
}};

struct FdRenamedResource { const char* src; const char* dst; };
// ROM-derived, byte-identical to an MM resource under a different name (voice grunts, MM_Jumps anim
// data, swirl textures, HUD icons). Copied from the temp MM extract under the FD name.
static const std::array<FdRenamedResource, 15> kFdRenamedRomPaths = {{
    { "audio/samples/SAMPLE_0_167_META", "custom/fd_voice/09" },
    { "audio/samples/SAMPLE_0_169_META", "custom/fd_voice/0A" },
    { "audio/samples/SAMPLE_0_171_META", "custom/fd_voice/0B" },
    { "audio/samples/SAMPLE_0_173_META", "custom/fd_voice/0C" },
    { "audio/samples/SAMPLE_0_175_META", "custom/fd_voice/0D" },
    { "audio/samples/SAMPLE_0_177_META", "custom/fd_voice/0E" },
    { "icon_item_static_yar/gItemIconFierceDeityMaskTex", "textures/icon_item_static/gFierceDeityMaskTex" },
    { "icon_item_static_yar/gItemIconFierceDeitySwordTex", "textures/icon_item_static/gFierceDeitySwordTex" },
    { "item_name_static/gItemNameFierceDeitysMaskENGTex", "textures/item_name_static/gFierceDeityMaskItemNameENGTex" },
    { "misc/link_animetion/gPlayerAnim_link_normal_newroll_jump_20f_Data", "misc/link_animetion/mmjumps_front_flip_jump_data" },
    { "misc/link_animetion/gPlayerAnim_link_normal_newroll_jump_end_20f_Data", "misc/link_animetion/mmjumps_front_flip_land_data" },
    { "misc/link_animetion/gPlayerAnim_link_normal_newside_jump_20f_Data", "misc/link_animetion/mmjumps_somersault_jump_data" },
    { "misc/link_animetion/gPlayerAnim_link_normal_newside_jump_end_20f_Data", "misc/link_animetion/mmjumps_somersault_land_data" },
    { "objects/gameplay_keep/gameplay_keep_Tex_054D90", "objects/gameplay_keep/gTransformEffectFirstTex" },
    { "objects/gameplay_keep/gameplay_keep_Tex_054E10", "objects/gameplay_keep/gTransformEffectSecondTex" },
}};

static const std::array<const char*, 35> kFdBundledPaths = {
    "custom/fonts/FD_GetAMask",
    "custom/fonts/FD_TransformAdult",
    "custom/fonts/FD_TransformChild",
    "custom/fonts/FD_TransformFaceChange",
    "custom/fonts/FD_TransformFlash",
    "custom/fonts/FD_TransformMaskAttach",
    "custom/music/FD_GetAMask",
    "custom/music/FD_TransformAdult",
    "custom/music/FD_TransformChild",
    "custom/music/FD_TransformFaceChange",
    "custom/music/FD_TransformFlash",
    "custom/music/FD_TransformMaskAttach",
    "custom/samples/fd/Adult_Transform",
    "custom/samples/fd/Adult_Transform.wav",
    "custom/samples/fd/Child_Transform",
    "custom/samples/fd/Child_Transform.wav",
    "custom/samples/fd/Flash_Transform",
    "custom/samples/fd/Flash_Transform.wav",
    "custom/samples/fd/Get_A_Mask",
    "custom/samples/fd/Get_A_Mask.wav",
    "custom/samples/fd/Mask_Attach",
    "custom/samples/fd/Mask_Attach.wav",
    "custom/samples/fd/Mask_Untransform",
    "custom/samples/fd/Mask_Untransform.wav",
    "objects/gameplay_keep/gPlayerAnim_mmjumps_front_flip_jump",
    "objects/gameplay_keep/gPlayerAnim_mmjumps_front_flip_land",
    "objects/gameplay_keep/gPlayerAnim_mmjumps_somersault_jump",
    "objects/gameplay_keep/gPlayerAnim_mmjumps_somersault_land",
    "objects/gameplay_keep/gTransformEffectDL",
    "objects/gameplay_keep/gTransformEffectVtx",
    "objects/object_link_boy/gFdFairyOcarinaDL",
    "objects/object_link_boy/gFdOotOcarinaDL",
    "objects/object_link_boy/gLinkFierceDeityRightHandHoldingOotFarDL",
    "objects/object_link_boy/gLinkFierceDeityRightHandHoldingOotNearDL",
    "objects/object_link_boy/gLinkFierceDeityRightHandNearDL",
};

#endif
